{
 "title": "Neonlabs performance test",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PROXY: Restart transaction with timeout",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "block_contract_request_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "k6_block_contract_request_time_1 / 1000",
       "legendFormat": "iterative: {{iterative}}"
      }
     ]
    },
    {
     "title": "block_contract_errors_in_receipt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "k6_block_contract_errors_in_receipt_counter",
       "legendFormat": "iterative: {{iterative}}, error: {{error}}"
      },
      {
       "expr": "sum(k6_block_contract_errors_in_receipt_counter)",
       "legendFormat": "Total errors"
      }
     ]
    },
    {
     "title": "send_block_contract_requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "k6_send_block_contract_requests_counter",
       "legendFormat": "iterative: {{iterative}}"
      },
      {
       "expr": "sum(k6_send_block_contract_requests_counter)",
       "legendFormat": "Total requests"
      }
     ]
    },
    {
     "title": "block_contract_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "k6_block_contract_errors_counter",
       "legendFormat": "iterative: {{iterative}}, error: {{error}}"
      },
      {
       "expr": "sum(k6_block_contract_errors_counter)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "TRACER API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
       "legendFormat": "VUs"
      }
     ]
    },
    {
     "title": "Users",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
       "legendFormat": "VUs"
      }
     ]
    },
    {
     "title": "RPS historical methods",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "irate(k6_tracer_eth_call_requests_counter{})[$__rate_interval]",
       "legendFormat": "{{scenario}}"
      },
      {
       "expr": "irate(k6_tracer_eth_get_balance_requests_counter{})[$__rate_interval]",
       "legendFormat": "{{scenario}}"
      },
      {
       "expr": "irate(k6_tracer_eth_get_transaction_count_requests_counter{})[$__rate_interval]",
       "legendFormat": "{{scenario}}"
      },
      {
       "expr": "irate(k6_tracer_eth_get_storage_at_requests_counter{})[$__rate_interval]",
       "legendFormat": "{{scenario}}"
      }
     ]
    },
    {
     "title": "RPS debug trace transaction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "irate(k6_debug_trace_transaction_requests_counter{})[$__rate_interval]",
       "legendFormat": "{{scenario}}"
      }
     ]
    },
    {
     "title": "Aggregated RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 44 },
     "targets": [
      {
       "expr": "sum(irate(k6_tracer_eth_call_requests_counter{})[$__rate_interval], irate(k6_tracer_eth_get_balance_requests_counter{})[$__rate_interval], irate(k6_tracer_eth_get_transaction_count_requests_counter{})[$__rate_interval], irate(k6_tracer_eth_get_storage_at_requests_counter{})[$__rate_interval], irate(k6_debug_trace_transaction_requests_counter{})[$__rate_interval])",
       "legendFormat": "sum rate rps per 15s interval"
      }
     ]
    },
    {
     "title": "Errors in response",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "k6_tracer_eth_get_transaction_count_request_errors_counter{}",
       "legendFormat": "eth_get_transaction_count"
      },
      {
       "expr": "k6_tracer_eth_get_balance_request_errors_counter{}",
       "legendFormat": "eth_get_balance"
      },
      {
       "expr": "k6_tracer_eth_call_request_errors_counter{}",
       "legendFormat": "eth_call"
      },
      {
       "expr": "k6_debug_trace_transaction_request_errors_counter{}",
       "legendFormat": "debug_trace_transaction"
      },
      {
       "expr": "k6_tracer_eth_get_storage_at_request_errors_counter{}",
       "legendFormat": "eth_get_storage_at"
      }
     ]
    },
    {
     "title": "Requests Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "k6_tracer_eth_get_storage_at_errors_counter{}",
       "legendFormat": "eth_get_storage_at"
      },
      {
       "expr": "k6_tracer_eth_get_transaction_count_errors_counter{}",
       "legendFormat": "eth_get_transaction_count"
      },
      {
       "expr": "k6_tracer_eth_get_balance_errors_counter{}",
       "legendFormat": "eth_get_balance"
      },
      {
       "expr": "k6_tracer_eth_call_errors_counter{}",
       "legendFormat": "eth_call"
      },
      {
       "expr": "k6_debug_trace_transaction_errors_counter{}",
       "legendFormat": "debug_trace_transaction"
      }
     ]
    },
    {
     "title": "Requests Time Historical Methods 0.95%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_tracer_eth_call_request_time_0.95{})[$__interval]",
       "legendFormat": "eth_call"
      },
      {
       "expr": "avg(k6_tracer_eth_get_balance_request_time_0.95{})[$__interval]",
       "legendFormat": "eth_get_balance"
      },
      {
       "expr": "avg(k6_tracer_eth_get_storage_at_request_time_0.95{})[$__interval]",
       "legendFormat": "eth_get_storage_at"
      },
      {
       "expr": "avg(k6_tracer_eth_get_transaction_count_request_time_0.95{})[$__interval]",
       "legendFormat": "eth_get_transaction_count"
      }
     ]
    },
    {
     "title": "Requests Time Trace Tx 0.95%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_debug_trace_transaction_request_time_0.95{})[$__interval]",
       "legendFormat": "debug_trace_transaction"
      }
     ]
    },
    {
     "title": "Requests Time Historical Methods 1%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_tracer_eth_get_balance_request_time_1{})[$__interval]",
       "legendFormat": "eth_get_balance"
      },
      {
       "expr": "avg(k6_tracer_eth_call_request_time_1{})[$__interval]",
       "legendFormat": "eth_call"
      },
      {
       "expr": "avg(k6_tracer_eth_get_storage_at_request_time_1{})[$__interval]",
       "legendFormat": "eth_get_storage_at"
      },
      {
       "expr": "avg(k6_tracer_eth_get_transaction_count_request_time_1{})[$__interval]",
       "legendFormat": "eth_get_transaction_count"
      }
     ]
    },
    {
     "title": "Requests Time Trace Tx 1%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_debug_trace_transaction_request_time_1{})[$__interval]",
       "legendFormat": "debug_trace_transaction"
      }
     ]
    }
   ]
  },
  {
   "title": "PROXY: Aggregated Params",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
       "legendFormat": "VUs"
      }
     ]
    },
    {
     "title": "Users",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
     "targets": [
      {
       "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
       "legendFormat": "VUs"
      }
     ]
    },
    {
     "title": "RPS eth_* methods",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "irate(k6_ethereum_req_duration_count{})[$__rate_interval]",
       "legendFormat": "{{call}}"
      }
     ]
    },
    {
     "title": "Aggregated RPS eth_* methods",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
     "targets": [
      {
       "expr": "sum(irate(k6_ethereum_req_duration_count{})[$__rate_interval])",
       "legendFormat": "{{call}}"
      }
     ]
    },
    {
     "title": "Requests Time eth_* 0.95%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (call) (k6_ethereum_req_duration_0.95{})[$__interval]",
       "legendFormat": "{{call}}"
      }
     ]
    },
    {
     "title": "Requests Time eth_* 1%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (call) (k6_ethereum_req_duration_1{})[$__interval]",
       "legendFormat": "{{call}}"
      }
     ]
    },
    {
     "title": "Requests eth_* Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
     "targets": [
      {
       "expr": "irate(k6_ethereum_req_error_counter{})[$__rate_interval]",
       "legendFormat": "{{call}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PROXY: Send Neon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS send Neon",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "irate(k6_send_neon_request_time_count{})[$__rate_interval]",
       "legendFormat": "send Neon"
      }
     ]
    },
    {
     "title": "Send Neon Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
     "targets": [
      {
       "expr": "irate(k6_send_neon_errors_count{})[$__rate_interval]",
       "legendFormat": "send neon error"
      }
     ]
    },
    {
     "title": "Requests Time send Neon 0.95%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_send_neon_request_time_0.95{})[$__interval]",
       "legendFormat": "send Neon time"
      }
     ]
    },
    {
     "title": "Requests Time send Neon 1%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_send_neon_request_time_1{})[$__interval]",
       "legendFormat": "send Neon time"
      }
     ]
    }
   ]
  },
  {
   "title": "PROXY: Send ERC20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS send ERC20",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "irate(k6_send_erc20_requests_counter{})[$__rate_interval]",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Send ERC20 Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "irate(k6_send_erc20_errors_count{})[$__rate_interval]",
       "legendFormat": "erc20 errors"
      }
     ]
    },
    {
     "title": "Requests Time send ERC20 0.95%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_send_erc20_request_time_0.95{})[$__interval]",
       "legendFormat": "send erc20 time"
      }
     ]
    },
    {
     "title": "Requests Time send ERC20 1%tile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(k6_send_erc20_request_time_1{})[$__interval]",
       "legendFormat": "send erc20 time"
      }
     ]
    }
   ]
  },
  {
   "title": "k6 Params",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Iterations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "irate(k6_iterations_counter{})[$__rate_interval]",
       "legendFormat": "{{scenario}}"
      }
     ]
    },
    {
     "title": "Iterations duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "avg(k6_iteration_duration_1{})", "legendFormat": "avg duration" }
     ]
    }
   ]
  }
 ]
}