# syntax=docker/dockerfile:1.4

ARG OZ_TAG
ARG DOCKER_HUB_ORG_NAME
FROM $DOCKER_HUB_ORG_NAME/openzeppelin-contracts:$OZ_TAG AS oz-contracts
FROM ghcr.io/astral-sh/uv:python3.10-bookworm-slim AS builder

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install common dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
# Prepare repo for node 18
    apt-get install -y software-properties-common python3-lxml ca-certificates curl gnupg git && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
# Install py3.10 from deadsnakes repository and pip from standard ubuntu packages
    apt-get update && \
    apt-get install -y nodejs build-essential

COPY ./deploy/requirements/* /opt/neon-tests/

WORKDIR /opt/neon-tests
RUN uv venv

ENV VIRTUAL_ENV=.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN uv pip install -r /opt/neon-tests/click.txt

COPY ./ /opt/neon-tests

RUN python3 ./clickfile.py requirements -d all

ARG DOCKER_HUB_ORG_NAME
ENV DOCKER_HUB_ORG_NAME=${DOCKER_HUB_ORG_NAME}
ARG CONTRACTS_BRANCH
RUN python3 ./clickfile.py update-contracts --branch ${CONTRACTS_BRANCH}

RUN rm -rf /opt/neon-tests/compatibility/openzeppelin-contracts
COPY --from=oz-contracts /usr/src/app /opt/neon-tests/compatibility/openzeppelin-contracts
COPY --from=oz-contracts /root/.cache/hardhat-nodejs  /root/.cache/hardhat-nodejs
RUN cd ./compatibility/openzeppelin-contracts && docker/compile_contracts.sh

# Download solc separately as hardhat implementation is flaky
ENV DOWNLOAD_PATH="/root/.cache/hardhat-nodejs/compilers-v2/linux-amd64" \
    REPOSITORY_PATH="https://binaries.soliditylang.org/linux-amd64" \
    SOLC_BINARY="solc-linux-amd64-v0.7.6+commit.7338295f"
RUN mkdir -p ${DOWNLOAD_PATH} && \
    curl -o ${DOWNLOAD_PATH}/${SOLC_BINARY} ${REPOSITORY_PATH}/${SOLC_BINARY} && \
    curl -o ${DOWNLOAD_PATH}/list.json ${REPOSITORY_PATH}/list.json && \
    chmod -R 755 ${DOWNLOAD_PATH}

# Create a minimal final image with just /opt/neon-tests
FROM scratch AS final
COPY --from=builder /opt/neon-tests/.venv /opt/neon-tests/.venv
COPY --from=builder /opt/neon-tests/contracts/external/ /opt/neon-tests/contracts/external/
COPY --from=builder /opt/neon-tests/compatibility/openzeppelin-contracts /opt/neon-tests/compatibility/openzeppelin-contracts
COPY --from=builder /root/.cache/hardhat-nodejs  /root/.cache/hardhat-nodejs
