version: '3.5'
services:

  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.87.0
    depends_on:
      - 'victoriametrics'
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./.docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--remoteWrite.url=http://victoriametrics:8428/api/v1/write'
    networks:
      - neonlabs
    restart: always

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.87.0
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
    networks:
      - neonlabs
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - 'victoriametrics'
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./.docker/provisioning/:/etc/grafana/provisioning/
      - ./.docker/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - neonlabs
    restart: always

volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}

networks:
  neonlabs:
    driver: bridge